### ISSUE TITLE
10/22 Extracting Mod Contents

### ISSUE THREAD

**Issue by JackBNimble** [azraerl/serenity#5]
Wabbajack install is stuck at "10/22 Extracting Mod contents".

I've waited over an hour and also tried restarting Wabbajack. 

![Screenshot 2021-08-22 121039](https://user-images.githubusercontent.com/24818386/130363937-9d55cf11-b03a-4f80-b297-85f2338dee7c.jpg)

**Comment by azraerl** [comment]
Hey, it's better if you could join discord to talk through - either Wabbajack or Emporium.

Wabbajack log file would be the most helpful. But meanwhile you could try to delete ``D:\downloaded_mod_lists\serenity.wabbajack`` and re-download it. On other hand, you probably want to have Wabbajack installed into a separate folder instead of root of disk ``D:`` --- that is another potential reason of problem.

**Comment by JackBNimble** [comment]
Thank you for the response. 

I left the installer running for about three hours and it finished; from what I've learned online it may have just taken a very long to process a particular mod, likely high res textures. I'm closing this ticket.
