### ISSUE TITLE
Installation fails because ENB Version is not available any more

### ISSUE THREAD

**Issue by Kirschi** [azraerl/serenity#8]
**Describe the bug**
Did a normal installation and everything loaded fine until ENB. The error from the logs is:

31.98 - Download failed for enbseries_skyrimse_v0462.zip and no upgrade from this download source is possible
32.59 - Unable to download enbseries_skyrimse_v0462.zip (HTTPDownloader+State|http://enbdev.com/enbseries_skyrimse_v0462.zip)
32.59 - Cannot continue, was unable to download one or more archives

The link doesn't work when opening in the browser and I could not find a backup anywhere. I guess they took it down because 0.463 is available. Tried to fool Wabberjack by using 463 and renaming it to 462 but of course that doesn't work because of hash check.

**To Reproduce**
Well, install Serenity with Wabberjack

**Expected behavior**
It downloads a working version.

**Modlist version**
1.6.2.1

**Comment by azraerl** [comment]
Please follow next steps:
1. Open folder which you've picked as Serenity downloads in Wabbajack
2. Find and remove all `enbseries_skyrimse_v0462**` files
3. Download [enbseries_skyrimse_v0462.zip](https://cdn.discordapp.com/attachments/717201285496963094/887449518059188284/enbseries_skyrimse_v0462.zip)
4. Place it into that folder and run Wabbajack install once again

Also you may our join dedicated Serenity discord - [Emporio's Emporium](https://discord.gg/haVcdTvCce)

**Comment by Kirschi** [comment]
Thanks that did it!

**Comment by slaughter2012** [comment]
Hi, I'm also having a problem downloading the ENB. I have downloaded v0462.zip manually,
deleted all enb files v0462.zip as per azraerl steps into serenity dowload file section.
I still get "unable to download enb" and I can not install the game because " unable to download enb".
Here are the logs if it helps.
Thanks for all your hard work :)

0.16 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0.16 - Running in F:\2.5.3.1
0.17 - Detected Windows Version: 10.0.19043.0
0.17 - System settings - (31.9GB RAM) (4.8GB Page), Display: 3840 x 2160 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.17 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.19 - Steam: Found game Company of Heroes: Tales of Valor (20540) at "F:\SteamLibrary\steamapps\common\Company of Heroes"
0.19 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "F:\SteamLibrary\steamapps\common\Oblivion"
0.19 - Steam: Found game Company of Heroes  (228200) at "F:\SteamLibrary\steamapps\common\Company of Heroes Relaunch"
0.19 - Steam: Found game Company of Heroes: Eastern Front (317600) at "F:\SteamLibrary\steamapps\common\Company of Heroes Relaunch"
0.19 - Steam: Found game Company of Heroes: Europe at War (342370) at "F:\SteamLibrary\steamapps\common\Company of Heroes Relaunch"
0.19 - Steam: Found game Company of Heroes - Legacy Edition (4560) at "F:\SteamLibrary\steamapps\common\Company of Heroes"
0.19 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "F:\SteamLibrary\steamapps\common\Skyrim Special Edition"
0.19 - Steam: Found game Company of Heroes: Far East War (547180) at "F:\SteamLibrary\steamapps\common\Company of Heroes Relaunch"
0.19 - Steam: Found game Company of Heroes: Opposing Fronts (9340) at "F:\SteamLibrary\steamapps\common\Company of Heroes"
0.19 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\program files (x86)\steam\steamapps\common\Steamworks Shared"
0.19 - Steam: Found game Counter-Strike: Global Offensive (730) at "C:\program files (x86)\steam\steamapps\common\Counter-Strike Global Offensive"
0.19 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.19 - Steam: Found game Counter-Strike: Global Offensive (730) at "c:/program files (x86)/steam\steamapps\common\Counter-Strike Global Offensive"
0.19 - GOG: GOG was not found in the registry
0.2 - BethNet: Found game Creation Kit: Skyrim (10) at "F:\SteamLibrary\steamapps\common\Skyrim Special Edition"
0.2 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.2 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.4 - Wabbajack Version: 2.5.3.1
1.29 - Build server is alive
1.3 - Build server is alive
1.3 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
1.3 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
4.42 - Starting to install Serenity2
4.43 - Cleaning VFS, this may take a bit of time
4.44 - Starting Installer Task
4.44 - Installation has Started
4.44 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
4.7 - Configuring Processor
4.71 - Install Folder: F:\Serenity
4.71 - Downloads Folder: F:\Serenity\downloads
4.71 - Game Folder: F:\SteamLibrary\steamapps\common\Skyrim Special Edition
4.71 - Wabbajack Folder: F:\2.5.3.1
4.71 - Drive watcher is starting. Will warn at 8GB and error at 4GB
4.71 - Starting Drive watcher on F:\ currently 826.4GB free out of 931.5GB
4.71 - Validating Game ESMs
4.72 - Creating Output Folders
5.12 - Optimizing ModList
5.12 - Optimizing ModList directives
6 - Looking for files to delete
6.07 - Cleaning empty folders
6.39 - Looking for unmodified files
6.62 - Updating ModList
6.62 - Optimized 107919 directives to 107919 required
6.65 - Hashing Archives
6.65 - Looking for files to hash
6.7 - Found 1002 total files, 1007 matching filesize
6.79 - Downloading Missing Archives
6.79 - Missing 1 archives
6.79 - Getting Nexus API Key, if a browser appears, please accept
6.8 - Loading server whitelist
6.9 - Loaded permissions for 565 servers and 258 Google Drive files
6.9 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
6.99 - Downloading enbseries_skyrimse_v0462.zip
7.42 - Loading for alternative to nJ59BDEM0qc=
8.3 - Download failed for enbseries_skyrimse_v0462.zip and no upgrade from this download source is possible
8.63 - Hashing Remaining Archives
8.63 - Looking for files to hash
8.66 - Found 1003 total files, 1007 matching filesize
8.76 - Unable to download enbseries_skyrimse_v0462.zip (HTTPDownloader+State|http://enbdev.com/enbseries_skyrimse_v0462.zip)
8.76 - Cannot continue, was unable to download one or more archives
8.76 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
8.78 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
9.6 - File hash check (-42) 80fc51c51a3537edf59c681e3cd3999f61cf3cef736d769cb89de1afe8e246bc
